export const workers = [
    {
      id: "1",
      text: "Chairman & CEO",
      title: "Henry Bennett",
      img: "https://churchplusstorage.blob.core.windows.net/mediacontainer/man_face_e9749fad-85e8-4130-b553-37acc8acde61_20102021.png",
    },
    {
      id: "2",
      text: "QA Lead & Product Designer",
      title: "Emma Lynch",
      img: "https://churchplusstorage.blob.core.windows.net/mediacontainer/232aa2bcab929ff532ce660e80ccdb89_e9749fad-85e8-4130-b553-37acc8acde61_30112021.jpeg",
      parent: 1,
      dir: "vertical",
    },
    {
      id: "2.1",
      text: "QA",
      title: "Charles Little",
      img: "https://churchplusstorage.blob.core.windows.net/mediacontainer/03TB-KINGFISHER1-mediumSquareAt3X_e9749fad-85e8-4130-b553-37acc8acde61_30112021.jpeg",
      parent: 2,
    },
    {
      id: "2.2",
      text: "QA",
      title: "Douglas Riley",
      img: "https://churchplusstorage.blob.core.windows.net/mediacontainer/WhatsApp_Image_2021-08-06_at_11.28.16_e9749fad-85e8-4130-b553-37acc8acde61_06082021.jpeg",
      parent: 2,
    },
    {
      id: "2.3",
      text: "QA",
      title: "Eugene Foster",
      img: "./common/img/workers/avatar-5.png",
      parent: 2,
    },
    {
      id: "3",
      text: "Technical Director",
      title: "Jerry Wagner",
      img: "./common/img/workers/avatar-6.png",
      parent: 1,
    },
    {
      id: "3.1",
      text: "Team Lead",
      title: "Mark Nichols",
      img: "./common/img/workers/avatar-7.png",
      parent: 3,
    },
    {
      id: "3.1.1",
      text: "Programmer",
      title: "Sean Parker",
      img: "./common/img/workers/avatar-8.png",
      parent: 3.1,
      open: false,
    },
    {
      id: "3.1.1.1",
      text: "Junior",
      title: "Laura Alvarez",
      img: "./common/img/workers/avatar-9.png",
      parent: "3.1.1",
    },
    {
      id: "4",
      text: "Manager",
      title: "Jonathan Lane",
      img: "./common/img/workers/avatar-10.png",
      parent: "1",
      dir: "vertical",
    },
    {
      id: "4.1",
      text: "Marketer",
      title: "Sandra Butler",
      img: "./common/img/workers/avatar-11.png",
      parent: "4",
    },
    {
      id: "4.2",
      text: "Designer",
      title: "Julie Green",
      img: "./common/img/workers/avatar-12.png",
      parent: "4",
    },
    {
      id: "4.3",
      text: "Sales Manager",
      title: "Richard Hicks",
      img: "./common/img/workers/avatar-13.png",
      parent: "4",
    },
    {
      id: "3.2",
      text: "Team Lead",
      title: "Nicholas Cruz",
      img: "./common/img/workers/avatar-14.png",
      parent: 3,
    },
    {
      id: "3.2.1",
      text: "Programmer",
      title: "Michael Shaw",
      img: "./common/img/workers/avatar-15.png",
      parent: "3.2",
    },
    {
      id: "3.2.1.1",
      text: "Junior",
      title: "John Flores",
      img: "./common/img/workers/avatar-16.png",
      parent: "3.2.1",
    },
  ];
  